version: '3.8'

services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
